### ISSUE TITLE
Failed to update layer information. Error: Not connected

### ISSUE THREAD

**Issue by anklav24** [Thomas-Smyth/SquadJS#279] opened 2023-02-02 02:49 UTC
Hi I often get this kind of RCON errors. How to prevent them?
```
фев 02 02:47:25 squad-vsrv taskset[1880709]: [SquadServer][1] Failed to update layer information. Error: Not connected.
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at file:///home/squad/SquadJS/main_server/core/rcon.js:301:16
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at new Promise (<anonymous>)
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at SquadRcon.write (file:///home/squad/SquadJS/main_server/core/rcon.js:299:12)
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at SquadRcon.execute (file:///home/squad/SquadJS/main_server/core/rcon.js:295:17)
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at SquadRcon.getCurrentMap (file:///home/squad/SquadJS/main_server/squad-server/rcon.js:123:33)
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at SquadServer.updateLayerInformation (file:///home/squad/SquadJS/main_server/squad-server/index.js:415:42)
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at listOnTimeout (internal/timers.js:557:17)
фев 02 02:47:25 squad-vsrv taskset[1880709]:     at processTimers (internal/timers.js:500:7)
```

**Comment by werewolfboy13** [comment] 2023-02-02 02:55
Check your RCON connection information.

**Comment by werewolfboy13** [comment] 2023-02-02 02:56
This may also be a duplicate of #262

**Comment by werewolfboy13** [comment] 2023-02-02 02:56
Correction #200 @ect0s

**Comment by anklav24** [comment] 2023-02-02 03:17
This happened from time to time. Do you mean the rcon config?
```
// Edit this IP to bind the RCON socket to an alternate IP address.
// Alternatively, set this from the command line with the argument:
//   RCONIP=0.0.0.0
IP=0.0.0.0

// Edit this IP to bind the RCON socket to an alternate port.
// Alternatively, set this from the command line with the argument:
//   RCONPORT=21114
Port=21124

// Set this to enable the usage of RCON with the given password for login.
// Leaving this empty will keep RCON turned off.
// Alternatively, set this from the command line with the argument:
//   RCONPASSWORD=MyPassword
Password=<<REDACTED>>

// Set this to set the maximum number of allowable concurrent RCON
// connections to the server.
// Alternatively, set this from the command line with the argument:
//   RCONMAXCONNECTIONS=5
MaxConnections=100

// Edit this to customize the number of seconds without contact from a connected
// console before the server checks to see if the session is still active, or if 
// it got disconnected. Supports values between 0 and 86400 (1 day). Set to zero 
// to disable the timeout.
// Alternatively, set this from the command line with the argument:
//   RCONCONNECTIONTIMEOUT=300
ConnectionTimeout=100

// Edit this to customize the number of seconds without contact from a connected
// console before the server sends a TCP KEEPALIVE to check if the session is
// still active, or if it got disconnected. Supports values between 30 and 3600 (1 hour).
// Alternatively, set this from the command line with the argument:
//   RCONSECONDSBEFORETIMEOUTCHECK=120
SecondsBeforeTimeoutCheck=30

// Edit this to customize the number of seconds the server will wait for the 
// console to authenticate when a connection has been established. Supports 
// values between 0 and 3600 (1 hour). Set to zero to disable the timeout.
// Alternatively, set this from the command line with the argument:
//   RCONSECONDSBEFORETIMEOUTCHECK=5
AuthenticationTimeout=10
```

**Comment by werewolfboy13** [comment] 2023-02-02 03:28
@anklav24 Please do not share RCON passes over github or discords please....

**Comment by werewolfboy13** [comment] 2023-02-02 03:29
Is your IP set correctly in your configs?

**Comment by anklav24** [comment] 2023-02-02 03:42
Thanks, I forgot about the password.
All things mostly work, but sometimes this error happens and everything crashes. I have to reload squad js until the rcon authentication is successful.

**Comment by werewolfboy13** [comment] 2023-02-02 03:43
I may direct you to another ticket but I pinged someone who has been trying to fix this issue for a while.

**Comment by ect0s** [comment] 2023-02-02 23:39
This, without more context, would appear to possibly be a duplicate of #200 and related issues. 

@anklav24 If your experiencing this often, you *could* try the open PR https://github.com/Team-Silver-Sphere/SquadJS/pull/267

If you can, more verbose RCON logging as well as more context around when this error occurred would let us confirm if the issue is the same as #200.

Leaving this open for now, until we confirm.

**Comment by anklav24** [comment] 2023-02-03 18:11
Ok, I'll try to catch the issue with more verbose RCON logs.

**Comment by werewolfboy13** [comment] 2023-11-01 06:40
Stale

**Closed as not planned by werewolfboy13** 2023-11-01 06:40 UTC
Labels: core bug
